<?php $this->partial("common/header"); ?>
    <!--SIDEBAR-->
    <?php $this->partial("common/slider",$commont_config); ?>
    <!--CONTENT-->
    <div id="content" class="white">
        <h1><img src="/images/icons/dashboard.png" alt="" /> 仪表盘</h1>
        <div class="bloc left">
            <div class="title">
                Dashboard
            </div>
            <div class="content dashboard">
                <div class="center">
                    <a href="#" class="shortcut">
                        <img src="/images/page.png" alt="" width="48" height="48"/>
                        Write an Article
                    </a>
                    <a href="#" class="shortcut">
                        <img src="/images/picture.png" alt="" width="48" height="48" />
                        Write an Article
                    </a>
                    <a href="#" class="shortcut">
                        <img src="/images/contact.png" alt="" width="48" height="48" />
                        Manage contacts
                    </a>
                    <a href="#" class="shortcut last">
                        <img src="/images/event.png" alt="" width="48" height="48" />
                        Manage events
                    </a>
                    <div class="cb"></div>
                </div>
                <p>Icons by <a href="http://icondrawer.com/">icondrawer.com</a></p>
            </div>
        </div>
        <div class="bloc right">
            <div class="title">
                Today
            </div>
            <div class="content">
                <div class="left">
                    <table class="noalt">
                        <thead>
                            <tr>
                                <th colspan="2"><em>Content</em></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><h4>460</h4></td>
                                <td>Posts</td>
                            </tr>
                            <tr>
                                <td><h4>12</h4></td>
                                <td>Pages</td>
                            </tr>
                            <tr>
                                <td><h4>5</h4></td>
                                <td>Categories</td>
                            </tr>
                            <tr>
                                <td><h4>20 000</h4></td>
                                <td>Contacts</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="right">
                    <table class="noalt">
                        <thead>
                            <tr>
                                <th colspan="2"><em>Comments</em></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><h4>46 000</h4></td>
                                <td class="good">Comments</td>
                            </tr>
                            <tr>
                                <td><h4>5</h4></td>
                                <td class="neutral">Waiting for validation</td>
                            </tr>
                            <tr>
                                <td><h4>0</h4></td>
                                <td class="bad">Spams</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="cb"></div>
            </div>
        </div>


        <div class="cb"></div>
        <div class="bloc">
            <div class="title">
                Shortcuts
            </div>
            <div class="content">
                <div class="cb"></div>
            </div>
        </div>

        <div class="bloc">
            <div class="title">
                Shortcuts
            </div>
            <div class="content">
                <a href="typography.html?p=typo" class="shortcut">
                    <img src="/images/icons/font.png" alt="" />
                    Typography
                </a>
                <a href="table.html?p=table" class="shortcut">
                    <img src="/images/icons/window.png" alt=""  width="32" height="32"/>
                    Table
                </a>
                <a href="notifications.html?p=notif" class="shortcut">
                    <img src="/images/icons/warning.png" alt=""  width="32" height="32"/>
                    Notifications
                </a>
                <a href="forms.html?p=forms" class="shortcut">
                    <img src="/images/icons/posts.png" alt=""  width="32" height="32"/>
                    Forms
                </a>
                <a href="charts.html?p=charts" class="shortcut">
                    <img src="/images/icons/chart.png" alt=""  width="32" height="32"/>
                    Charts
                </a>
                <a href="calendar.html?p=calendar" class="shortcut">
                    <img src="/images/icons/calendar.png" alt=""  width="32" height="32"/>
                    Calendar
                </a>
                <div class="cb"></div>
            </div>
        </div>
    </div>
</body>
</html>