<?php $this->partial("common/header"); ?>
    <!--SIDEBAR-->
     <?php $this->partial("common/slider",$commont_config); ?>
    <!--CONTENT-->
    <div id="content" class="white">
        <h1><img src="/images/icons/document-2.png" alt="" /> 待办事项</h1>

        <div class="bloc">
            <div class="title"></div>
            <div class="user_save">
                <a href="#" class="button save">　新建　</a>
            </div>
            <div class="todozone">
                <table>
                    <tr>
                        <td class="todozonetd">待办事项</td>
                        <td class="todozonetd">截止日期</td>
                        <td class="todozonetd">状态</td>
                        <td class="todozonetd">操作</td>
                    </tr>
                    <tr>
                        <td><a href="">oa开发 下一年的目标</a></td>
                        <td>2016-05-05</td>
                        <td>正在进行</td>
                        <td><a href="">删除</a></td>
                    </tr>
                </table>
                <div class="line"></div>
                 <table>
                    <tr>
                        <td class="todozonetd">已完成事项</td>
                        <td class="todozonetd">截止日期</td>
                        <td class="todozonetd">状态</td>
                        <td class="todozonetd">操作</td>
                    </tr>
                    <tr>
                        <td><a href="">oa开发 下一年的目标</a></td>
                        <td>2016-05-05</td>
                        <td>正在进行</td>
                        <td><a href="">删除</a></td>
                    </tr>
                    <tr>
                        <td><a href="">oa开发 下一年的目标</a></td>
                        <td>2016-05-05</td>
                        <td>正在进行</td>
                        <td><a href="">删除</a></td>
                    </tr>
                    <tr>
                        <td><a href="">oa开发 下一年的目标</a></td>
                        <td>2016-05-05</td>
                        <td>正在进行</td>
                        <td><a href="">删除</a></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    </body>
</html>